<?xml version="1.0" encoding="UTF-8"?>
<project
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.1.0</version>
        <relativePath/> </parent>
    <groupId>com.aroon4uu.cloud-run-multicontainer</groupId>
    <artifactId>cloud-run-multicontainer</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>cloudrun</name>
    <description>Cloud Run Multicontainer</description>
    <properties>
        <java.version>17</java.version>
		<maven.compiler.source>17</maven.compiler.source>
  		<maven.compiler.target>17</maven.compiler.target>
  		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.compiler.showDeprecation>true</maven.compiler.showDeprecation>
		<app.local.libpath>${project.basedir}/src/main/resources/lib</app.local.libpath>
		<app.id>cloud-run-multicontainer</app.id>
		<app.version>cloud-run-multicontainer</app.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
		    <groupId>jakarta.servlet</groupId>
		    <artifactId>jakarta.servlet-api</artifactId>
		    <scope>provided</scope>
		</dependency>

    </dependencies>

    <build>
    	<resources>
	        <resource>
	            <directory>${project.basedir}/src/main/resources</directory>
	            <filtering>true</filtering> 
            	<excludes>
                	<exclude>static/**</exclude> 
            	</excludes>
            	<includes>
                	<include>[^.]*</include>  
            	</includes>
	        </resource>
	    </resources>
    	<outputDirectory>${project.build.directory}/${project.build.finalName}/classes</outputDirectory>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                	<mainClass>com.aroon4uu.cloudrun.CloudRunApplication</mainClass> 
            	</configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>com.aroon4uu.cloudrun.CloudRunApplication</mainClass>
                </configuration>
            </plugin>
            <plugin>
			    <artifactId>maven-resources-plugin</artifactId>
			    <configuration>
			        <nonFilteredFileExtensions>
			            <nonFilteredFileExtension>pfx</nonFilteredFileExtension>
			            <nonFilteredFileExtension>jks</nonFilteredFileExtension>
			            <nonFilteredFileExtension>txt</nonFilteredFileExtension>
			            <nonFilteredFileExtension>properties</nonFilteredFileExtension>
			            <nonFilteredFileExtension>json</nonFilteredFileExtension>
					</nonFilteredFileExtensions>
			    </configuration>
			</plugin>
        </plugins>
    </build>
	<profiles>
		<profile>
	        <id>exclude-static</id>
	        <build>
	            <resources>
	                <resource>
	                    <directory>${project.basedir}/src/main/resources</directory>
	                    <excludes>
	                        <exclude>static/**</exclude>
	                    </excludes>
	                </resource>
	            </resources>
	        </build>
	    </profile> 
	</profiles>
</project>